-- tabela produtos
create table if not exists stg_dim_produtos(
	produto_id integer primary key,
	produto text,
	categoria text,
	preco_unitario numeric(10,2),
	marca text,
	fornecedor text
);

-- tabela clientes
create table if not exists stg_dim_cliente(
	cliente_id int
);


--tabela cidade
create table if not exists stg_dim_cidade(
	cidade_id int GENERATED BY DEFAULT AS IDENTITY (start with 500) primary key,
	cidade text,
	estado text
);

-- tabela tempo
create table if not exists stg_dim_tempo(
	data_id text not null primary key,
	data date not null,
	dia int,
	mes int,
	ano int
);

-- tabela localidade
create table if not exists stg_dim_localidade(
	local_cd_id int GENERATED BY DEFAULT AS IDENTITY (start with 200) primary key,
	centro_distribuicao text
);


-- tabela canal de venda
create table if not exists stg_dim_canal_vendas(
	canal_venda_id int GENERATED BY DEFAULT AS IDENTITY (start with 300) primary key,
	canal_venda text
);


-- tabela pagemento
create table if not exists stg_dim_pagamento(
	pagamento_id int GENERATED BY DEFAULT AS IDENTITY (start with 300)primary key,
	forma_pagamento text
);

-- tabela fato vendas
create table if not exists stg_fact_vendas(
	pedido_id int,
	data_pedido date,
	cliente_id int,
	produto_id int,
	quantidade int,
	desconto numeric(12, 2),
	frete numeric(12, 2),
	valor_total numeric(12, 2),
	canal_venda_id int,
	pagamento_id int,
	cidade_id int,
	status_pedido text

);

-- tabela fato devolucoes
create table if not exists stg_fact_devolucoes(
	devolucao_id int ,
	pedido_id int,
	data_devolucao date,
	cliente_id int,
	produto_id int,
	quantidade_devolvida int,
	valor_devolvido numeric(12, 2),
	motivo_devolucao text,
	status_devolucao text
);

--tabela fato estoque
create table if not exists stg_fact_estoque(
	produto_id INT,
	estoque_inicial int,
	estoque_minimo int,
	estoque_atual int,
	entradas_periodo int,
	local_cd_id INT 
)